volumes:
  es-data: {}

services:
  elasticsearch:
    build: .
    platform: linux/amd64
    environment:
      discovery.type: single-node
      cluster.name: docker-cluster
      bootstrap.memory_lock: 'true'
      # bootstrap.system_call_filter: 'false'
    # security_opt:
    #   - seccomp:unconfined
    ports:
      - 9200:9200
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
      - ./elastic-jvm.options:/usr/share/elasticsearch/config/jvm.options

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.23
    platform: linux/amd64
    ports:
      - 5601:5601
