; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

; Common settings
[common]
platform = espressif32
framework = arduino
monitor_speed = 115200

; LED panel (8x32 WS2812B) - Atom Lite G25 connection
[env:led_panel]
platform = ${common.platform}
board = m5stack-atom
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
    fastled/FastLED
build_src_filter = -<*> +<../examples/07_led_panel/>

; LED Hat (SCROLL TEXT / EYES mode switching)
[env:led_hat]
platform = ${common.platform}
board = m5stack-atom
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
    fastled/FastLED
build_src_filter = -<*> +<../examples/08_led_hat/>

; LED Badge (32x16, two panels stacked vertically, 3x7 slim font)
[env:led_badge]
platform = ${common.platform}
board = m5stack-atom
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
    fastled/FastLED
build_src_filter = -<*> +<../examples/09_led_badge/>
