source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'kaminari'
gem 'simple_form'
gem 'font-awesome-rails'
gem 'carrierwave'
gem 'rmagick'
gem 'fog'
gem 'fog-aws'
gem 'settingslogic'

gem 'simple_posts', path: '../simple_posts'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

