version: '3'
services:
  front_proxy:
    build:
      context: ./front_proxy
    volumes:
      - sockets:/var/run/glaaki
    ports:
      - 8000:80
  app:
    build:
      context: ./app
    volumes:
      - sockets:/var/run/glaaki
volumes:
  sockets:
