version: '3'
services:
  envoy:
    build:
      context: .
      dockerfile: dockerfiles/envoy/Dockerfile
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"

  nginx:
    image: nginx:stable-alpine
    expose:
      - "80"
