; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

; Common settings
[common]
platform = espressif32
framework = arduino
monitor_speed = 115200

; Atom Lite
[env:atom]
platform = ${common.platform}
board = m5stack-atom
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
    m5stack/M5Atom

; Atom Lite + Atomic Display Base (HDMI output)
[env:atom_display]
platform = ${common.platform}
board = m5stack-atom
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
lib_deps =
    m5stack/M5GFX
build_src_filter = -<*> +<../examples/05_display_base/>
