# frozen_string_literal: true

source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'

gem 'activesupport'
gem 'connection_pool'
gem 'redis'

group :development do
  gem 'pry'
end
