apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-test
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/corrupt952/sandbox
    targetRevision: main
    path: k8s-preview-env/charts/preview-env
    helm:
      parameters:
        - name: previewId
          value: "test"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
