version: '3'

services:
  app:
    container_name: app
    image: ruby:2.6
    volumes:
      - .:/app
    working_dir: /app
    depends_on: [db]
    tty: true
    stdin_open: true
    environment:
      SECRET_KEY_BASE: X
      RAILS_ENV: production

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
