name: Concurrency Test

on: [workflow_dispatch]

jobs:
  concurrency_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ben-z/gh-action-mutex@v1.0-alpha-6
      - run: |
          sleep 15
