name: Concurrency Test 2

on: [workflow_dispatch]

concurrency:
  hoge

jobs:
  concurrency_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sleep 15
