name: Concurrency Test

on: [workflow_dispatch]

concurrency:
  group: hoge
  cancel-in-progress: false

jobs:
  concurrency_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sleep 15
