name: Trigger Check Test

on:
  pull_request:
    branches:
      - main
      - master
    paths:
      - ".github/**/*.yml"
      - ".github/**/*.yaml"

jobs:
  check_diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print changed files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git branch --all
          FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} ${{ github.sha }})
          echo "Changed files in this PR: $FILES"
